# version: '3'

services:
  # Uncomment the following to use postgres
  postgres:
    restart: always
    image: postgres:15
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - '5432:5432'

  payload:
    image: node:22-alpine
    restart: always
    environment:
      DATABASE_URL: ${DATABASE_URI}
      PAYLOAD_SECRET: ${PAYLOAD_SECRET}
    ports:
      - '3000:3000'
    volumes:
      - .:/home/node/app
      - node_modules:/home/node/app/node_modules
    working_dir: /home/node/app/
    command: sh -c "corepack enable && corepack prepare pnpm@latest --activate && pnpm install && pnpm dev"
    depends_on:
      # - mongo
      - postgres
    env_file:
      - .env

volumes:
  data:
  pgdata:
  node_modules:
