services: # Postgres Database Service
  # Payload (Node.js App) Service
  payload:
    build:
      context: .
      dockerfile: Dockerfile.unopt
      extra_hosts:
        - 'host.docker.internal:host-gateway'
    extra_hosts:
      - 'host.docker.internal:host-gateway'

    # restart: always
    environment:
      DATABASE_URL: ${PAYLOAD_PUBLIC_DATABASE_URI}
      PAYLOAD_SECRET: ${PAYLOAD_SECRET}
    ports:
      - '3000:3000'

    volumes:
      - ./media:/app/media
    #   - .:/home/node/app
    # - node_modules:/home/node/app/node_modules
    # working_dir: /home/node/app/
    # depends_on:
    #   - postgres
    env_file:
      - .env
    networks:
      - my-network
  nginx:
    image: nginx:latest
    container_name: nginx-reverse-proxy
    restart: always
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - certs:/etc/letsencrypt:ro
    depends_on:
      - payload
    networks:
      - my-network

networks:
  my-network:
    external: true
volumes:
  media:
  certs:
