FROM node:22-alpine AS base

RUN apk add --no-cache libc6-compat
RUN corepack enable 
WORKDIR /app

COPY package.json ./ 
RUN pnpm install

COPY . .

RUN \
  if [ -f pnpm-lock.yaml ]; then pnpm run build; \
  else echo "Yaml not found." && exit 1; \
  fi

RUN addgroup --system --gid 1001 nodejs \
  && adduser --system --uid 1001 nextjs \
  && chown -R nextjs:nodejs .next

FROM base AS runner 
COPY --from=base /app/public ./public
COPY --from=base --chown=nextjs:nodejs /app/.next/standalone/. ./
COPY --from=base --chown=nextjs:nodejs /app/.next/static ./.next/static

USER nextjs

EXPOSE 3000

CMD ["node", "server.js"] 
