const services = [
    { id: 1, value: "Chip Tuning and ECU Mapping", myimgs: 'chip-tuning.jpg', info: "We optimize your vehicle's ECU for increased power, improved fuel efficiency, and enhanced driving dynamics using industry-leading tuning software." },
    { id: 2, value: "Stainless Steel Exhaust Systems", myimgs: "swift3.jpg", info: "Our high-quality stainless steel exhausts improve performance, resist corrosion, and deliver a deeper, more aggressive sound." },
    { id: 3, value: "Service and Maintenance", myimgs: "service-maintenance.jpg", info: "We provide expert maintenance, diagnostics, and performance-oriented services to keep your vehicle in peak condition."},
    { id: 4, value: "Dyno Tuning", myimgs: "dyno-tuning.jpg", info: "Our advanced dynamometer fine-tunes your engine for maximum power, efficiency, and customized performance." },
    { id: 5, value: "Turbocharger Conversions & Upgrades", myimgs: "turbocharger.jpg", info: "We install and upgrade turbochargers for significant power gains, improved throttle response, and optimized efficiency." },
    { id: 6, value: "Supercharger Conversions", myimgs: "supercharger.jpg", info: "Our supercharger conversions deliver instant power, improved acceleration, and a linear boost for ultimate performance." }
];

const car_brands = [{ value: "Suzuki Jimny", info: "The Suzuki Jimny is a popular choice for overlanding enthusiasts, known for its compact size and off-road capabilities. However, when fully equipped with overlanding gear, it may require additional power to handle challenging terrains effectively. One way to enhance its performance is by upgrading to the SG Performance Garrett GT17 Turbo, which can boost the engine's output to 130kW and 250Nm. In addition to the power upgrade, customizing the exhaust system, such as adding a dual exit exhaust, can further enhance the vehicle's performance and sound. Suspension upgrades, like the Tough Dog shock absorbers with custom powder-coated springs, can improve ride comfort and handling. For better safety and control, upgrading the braking system, for instance with Powerbrake components, is also a valuable addition to an overlanding Jimny build.", srcimg: "jimny1.jpg" },
{ value: "Land Cruiser", info: "The Toyota Land Cruiser is a legendary choice among off-road enthusiasts, celebrated for its rugged durability and exceptional off-road prowess. However, when outfitted with extensive overlanding gear, it may require additional power and modifications to maintain peak performance in challenging terrains. Upgrading to a performance-enhancing turbocharger, such as the Garrett GT2860, can significantly increase the engine's output, delivering more power and torque for demanding off-road conditions. Customizing the exhaust system with a high-flow, stainless steel setup can improve both the vehicle’s performance and exhaust note. Suspension enhancements, like Old Man Emu shock absorbers paired with heavy-duty coil springs, can further refine the ride quality and handling, ensuring comfort and control on rough trails. Additionally, upgrading the braking system with components like Brembo high-performance brakes can provide superior stopping power, a crucial aspect for the safety and reliability of any overlanding Land Cruiser build.", srcimg: "land-cruiser.jpg" },
{ value: "BMW", info: "BMW enthusiasts seeking to elevate their vehicle's performance can turn to SG Performance for expert tuning and upgrades. Specializing in BMW performance enhancements, SG Performance offers ECU remapping services that optimize engine parameters, unlocking additional power and torque for a more dynamic driving experience. For those looking to push the limits, SG Performance provides turbocharger upgrades and performance intake systems that significantly improve acceleration and throttle response. Their high-flow exhaust systems not only increase power output but also enhance the vehicle’s sound, adding a more aggressive tone. Additionally, SG Performance offers suspension upgrades, including performance coilovers and sway bars, designed to improve handling, cornering, and stability at high speeds. To match the increased performance, SG Performance also delivers high-performance braking systems with larger calipers and rotors for superior stopping power. With these comprehensive BMW tuning solutions, SG Performance helps drivers achieve a truly customized and exhilarating driving experience.", srcimg: 'jimny1.jpg' },
{ value: "Suzuki Swift Sport", info: "The Suzuki Swift Sport is an agile choice for hatch-back enthusiasts, known for its compact size and handling capabilities. One way to enhance its performance is by upgrading your turbo, down pipes, exhaust system or remapping your ECU. In addition to the power upgrade, customizing the exhaust system, such as adding a dual exit exhaust, can further enhance the vehicle's performance and sound. Suspension upgrades, like the Tough Dog shock absorbers with custom powder-coated springs, can improve ride comfort and handling. For better safety and control, upgrading the braking system and steering components, is also a valuable addition to a high performance Suzuki Swift build.", srcimg: "swift1.jpg" },
{ value: 'Porsche', info: "Porsche, the prestigious name in German engineering, has repeatedly claimed the title for the fastest Nürburgring lap times, showcasing its unmatched prowess in high-performance sports cars. At SGPerformance, we take pride in pushing these limits even further. Our bespoke modifications include precision-tuned exhaust systems, state-of-the-art aerodynamic enhancements, and advanced suspension upgrades. We specialize in turbocharger and performance intake system upgrades, designed to boost acceleration and throttle response. With our expert tuning, your Porsche will not only meet but exceed the performance standards set by its remarkable heritage.", imgsrc: 'porsche.jpg' },
{ value: 'Audi', info: "Audi, a symbol of cutting- edge innovation and luxury in the automotive world, has long been celebrated for its unparalleled blend of performance and sophistication.At SGPerformance, we elevate this excellence to new heights.Our custom modifications are crafted to enhance every aspect of your Audi, from meticulously engineered stainless steel exhaust systems to aerodynamic upgrades that improve stability and control.We specialize in advanced ECU remapping and turbocharger enhancements, designed to deliver explosive acceleration and seamless power delivery.With our expert tuning, your Audi will transcend its already remarkable standards, offering a driving experience that’s both exhilarating and refined.", myimg: 'audi.jpg' }
];

function getServices() {
    return services;
}

function getCarBrands() {
    return car_brands;
}
export default { getServices, getCarBrands };